"""Shared Python validation and generated ProtoJSON consumers for trading-core."""

from .parquet_schema import (
    PARQUET_SCHEMA_DESCRIPTOR_METADATA_KEY,
    PARQUET_SCHEMA_FINGERPRINT_METADATA_KEY,
    load_trusted_parquet_schema_registry,
    trusted_parquet_schema_descriptor,
    trusted_parquet_schema_metadata,
    trusted_parquet_schema_sha256,
    validate_optional_parquet_schema_metadata,
)
from .protojson import (
    dataset_manifest_v2_protojson_bytes,
    dataset_completion_evidence_v2_protojson_bytes,
    dataset_completion_evidence_v2_sha256,
    finite_batch_seal_receipt_protojson_bytes,
    finite_batch_seal_receipt_sha256,
    parse_dataset_manifest_v2_json,
    parse_dataset_manifest_v2_protojson,
    parse_us_equity_trade_bar_v2_protojson,
    validate_bar_v2_completion_evidence_reference,
    validate_us_equity_trade_bar_v2_against_manifest,
)
from .raw_frame import (
    MARKET_EVENT_V3_SCHEMA_ID,
    MARKET_RAW_FRAME_V2_SCHEMA_ID,
    MARKET_RAW_JSON_FRAME_V2_SCHEMA_ID,
    validate_capture_instance_id_v2,
    validate_event_against_raw_frame_row_v2,
    validate_market_event_row_v3,
    validate_raw_event_chunk_v2,
    validate_raw_frame_row_v2,
)

__all__ = [
    "load_trusted_parquet_schema_registry",
    "PARQUET_SCHEMA_DESCRIPTOR_METADATA_KEY",
    "PARQUET_SCHEMA_FINGERPRINT_METADATA_KEY",
    "trusted_parquet_schema_descriptor",
    "trusted_parquet_schema_metadata",
    "trusted_parquet_schema_sha256",
    "validate_optional_parquet_schema_metadata",
    "parse_dataset_manifest_v2_json",
    "parse_dataset_manifest_v2_protojson",
    "dataset_manifest_v2_protojson_bytes",
    "finite_batch_seal_receipt_protojson_bytes",
    "finite_batch_seal_receipt_sha256",
    "dataset_completion_evidence_v2_protojson_bytes",
    "dataset_completion_evidence_v2_sha256",
    "validate_bar_v2_completion_evidence_reference",
    "parse_us_equity_trade_bar_v2_protojson",
    "validate_us_equity_trade_bar_v2_against_manifest",
    "MARKET_EVENT_V3_SCHEMA_ID",
    "MARKET_RAW_FRAME_V2_SCHEMA_ID",
    "MARKET_RAW_JSON_FRAME_V2_SCHEMA_ID",
    "validate_capture_instance_id_v2",
    "validate_raw_frame_row_v2",
    "validate_market_event_row_v3",
    "validate_event_against_raw_frame_row_v2",
    "validate_raw_event_chunk_v2",
]
