#!/usr/bin/env python3
"""Copy the root Parquet schema registry into the distributable Python package."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "schemas/fixtures/parquet-schema-registry.json"
DESTINATION = ROOT / "python/lqepoch_contracts/resources/parquet-schema-registry.json"
TYPESCRIPT_DESTINATION = ROOT / "typescript/src/contracts/parquet-schema-registry.ts"


def typescript_registry_source(source_bytes: bytes) -> bytes:
    import json

    registry = json.loads(source_bytes)
    payload = json.dumps(registry, ensure_ascii=False, sort_keys=True, indent=2)
    return (
        "// Generated by scripts/sync-parquet-schema-registry.py from the root registry.\n"
        f"export const TRUSTED_PARQUET_SCHEMA_REGISTRY = {payload} as const;\n"
    ).encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of updating when the generated wheel resource is stale",
    )
    args = parser.parse_args()
    source_bytes = SOURCE.read_bytes()
    typescript_bytes = typescript_registry_source(source_bytes)
    if args.check:
        if not DESTINATION.is_file() or DESTINATION.read_bytes() != source_bytes:
            parser.error("Python wheel registry is stale; run scripts/sync-parquet-schema-registry.py")
        if not TYPESCRIPT_DESTINATION.is_file() or TYPESCRIPT_DESTINATION.read_bytes() != typescript_bytes:
            parser.error("TypeScript registry is stale; run scripts/sync-parquet-schema-registry.py")
        return 0

    DESTINATION.parent.mkdir(parents=True, exist_ok=True)
    DESTINATION.write_bytes(source_bytes)
    TYPESCRIPT_DESTINATION.write_bytes(typescript_bytes)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
